
CREATE TABLE LDGR_HDR
(
	LDGR_ID               INTEGER NOT NULL ,
	DCN                   VARCHAR(20),
	CLM_LN_ID             INTEGER,
	SVC_ID                INTEGER,
	SVC_NM                VARCHAR(50),
	SVC_DT                DATE,
	PROC_DT               TIMESTAMP,
	NTWK_CD               CHAR(3),
	NTWK_TIER_NM          VARCHAR(10),
	PLN_ID                INTEGER,
	ALWD_AMT              DECIMAL(10,2),
	MBR_ID                VARCHAR(16),
	SUB_ID                VARCHAR(16),
	UOM_NM                VARCHAR(10),
	ACCUM_TYP_NM          VARCHAR(25),
	VEND_XACTN_ID         VARCHAR(20)
);

CREATE UNIQUE INDEX XPKLEDGER_HEADER ON LDGR_HDR
(
	LDGR_ID
);

ALTER TABLE LDGR_HDR
	ADD CONSTRAINT XPKLEDGER_HEADER  PRIMARY KEY (LDGR_ID);

CREATE TABLE LDGR_SUM
(
	LDGR_SUM_ID           INTEGER NOT NULL ,
	LDGR_ID               INTEGER NOT NULL ,
	ACCUM_TYP_NM          VARCHAR(25),
	MBR_ID                VARCHAR(16),
	NTWK_CD               CHAR(3),
	NTWK_TIER_NM          VARCHAR(10),
	END_DT                DATE,
	EFF_DT                DATE,
	PLN_ID                INTEGER,
	SUB_ID                VARCHAR(16),
	AMT                   DECIMAL(10,2),
	MAX_AMT               DECIMAL(10,2),
	MAX_VST_CNT           INTEGER,
	UOM_NM                VARCHAR(10)
);

CREATE UNIQUE INDEX XPKLEDGER_SUMMARY ON LDGR_SUM
(
	LDGR_SUM_ID
);

ALTER TABLE LDGR_SUM
	ADD CONSTRAINT XPKLEDGER_SUMMARY  PRIMARY KEY (LDGR_SUM_ID);

CREATE UNIQUE INDEX XAK1LEDGER_SUMMARY ON LDGR_SUM
(
	ACCUM_TYP_NM,
	MBR_ID,
	NTWK_CD,
	NTWK_TIER_NM,
	END_DT
);

CREATE INDEX XIF1LEDGER_SUMMARY ON LDGR_SUM
(
	LDGR_ID
);

CREATE TABLE LDGR_ENTRY
(
	LDGR_ENTRY_ID         INTEGER NOT NULL ,
	PRIMY_LDGR_ENTRY_ID   INTEGER,
	LDGR_ID               INTEGER NOT NULL ,
	ACCUM_TYP_NM          VARCHAR(25),
	ROLE_NM               VARCHAR(10),
	CST_SHR_TIER_NM       VARCHAR(10),
	AMT                   DECIMAL(10,2),
	NTWK_CD               CHAR(3),
	SNPSHT_SUM_AMT        DECIMAL(10,2),
	UOM_NM                VARCHAR(10),
	SVC_DT                DATE
);

CREATE UNIQUE INDEX XPKLEDGER_ENTRY ON LDGR_ENTRY
(
	LDGR_ENTRY_ID
);

ALTER TABLE LDGR_ENTRY
	ADD CONSTRAINT XPKLEDGER_ENTRY  PRIMARY KEY (LDGR_ENTRY_ID);

CREATE INDEX XIF1LEDGER_ENTRY ON LDGR_ENTRY
(
	LDGR_ID
);

CREATE INDEX XIF2LEDGER_ENTRY ON LDGR_ENTRY
(
	PRIMY_LDGR_ENTRY_ID
);

ALTER TABLE LDGR_SUM
	ADD CONSTRAINT R_2  FOREIGN KEY (LDGR_ID) REFERENCES LDGR_HDR (LDGR_ID)
		ON DELETE NO ACTION;

ALTER TABLE LDGR_ENTRY
	ADD CONSTRAINT R_1  FOREIGN KEY (LDGR_ID) REFERENCES LDGR_HDR (LDGR_ID)
		ON DELETE NO ACTION;

ALTER TABLE LDGR_ENTRY
	ADD CONSTRAINT R_3  FOREIGN KEY (PRIMY_LDGR_ENTRY_ID) REFERENCES LDGR_ENTRY (LDGR_ENTRY_ID)
		ON DELETE NO ACTION;
		
CREATE SEQUENCE SEQ_LDGR_HDR AS INT START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE SEQ_LDGR_ENTRY AS INT START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE SEQ_LDGR_SUM AS INT START WITH 1 INCREMENT BY 1;

