SET CURRENT SQLID = 'CSYSDBAD' ;
SET CURRENT SCHEMA = 'CAUDB03' ;

---- • Changed MBR_ID from INTEGER to VARCHAR(16)




CREATE SEQUENCE LDGR_ID_SEQ
           AS BIGINT
         , START WITH 1
         , INCREMENT BY  1
         , NO CYCLE
         , NO ORDER
         , MINVALUE 1
         , NO MAXVALUE
         , CACHE 100
  ;

CREATE SEQUENCE LDGR_SUM_ID_SEQ
           AS BIGINT
         , START WITH 1
         , INCREMENT BY  1
         , NO CYCLE
         , NO ORDER
         , MINVALUE 1
         , NO MAXVALUE
         , CACHE 100
  ;

CREATE SEQUENCE LDGR_ENTRY_ID_SEQ
           AS BIGINT
         , START WITH 1
         , INCREMENT BY  1
         , NO CYCLE
         , NO ORDER
         , MINVALUE 1
         , NO MAXVALUE
         , CACHE 100
  ;

GRANT USAGE ON SEQUENCE
     LDGR_ID_SEQ
   , LDGR_SUM_ID_SEQ
   , LDGR_ENTRY_ID_SEQ
  TO CAUDV01A
  ;


SET CURRENT SQLID = 'CAUDB03' ;



CREATE DATABASE AUDS6050
	BUFFERPOOL BP16K4
	INDEXBP BP16K2
	STOGROUP AUGS01
	CCSID UNICODE;

CREATE  TABLESPACE AUS050
        IN AUDS6050
        USING STOGROUP AUGS01
           PRIQTY 180000
           SECQTY -1
           ERASE NO
        BUFFERPOOL BP16K4
        FREEPAGE 8
        PCTFREE  10
              FOR UPDATE -1
        MAXPARTITIONS 100
        SEGSIZE 64
        DSSIZE 64G
----    NO MEMBER CLUSTER NO
        GBPCACHE CHANGED
        LOCKSIZE ROW
        LOCKMAX SYSTEM
        MAXROWS 255
        TRACKMOD NO
        CLOSE YES
        COMPRESS YES
        DEFINE YES
        LOGGED
        CCSID UNICODE
    ;

CREATE TABLE LDGR_HDR
(
	LDGR_ID               BIGINT NOT NULL,
	DCN                   VARCHAR(20),
	CORP_ENT_CD           CHAR(03),
	CLM_LN_ID             INTEGER,
	SVC_ID                INTEGER,
	SVC_NM                VARCHAR(50),
	SVC_DT                DATE,
	PROC_DT               TIMESTAMP,
	NTWK_CD               CHAR(3),
	NTWK_TIER_NM          VARCHAR(10),
	PLN_ID                INTEGER,
	ALWD_AMT              DECIMAL(10,2),
	MBR_ID                VARCHAR(16),
	SUB_ID                VARCHAR(16),
	UOM_NM                VARCHAR(10),
	VEND_XACTN_ID         VARCHAR(20),
	PRIMARY KEY (LDGR_ID)
   )
   IN AUDS6050.AUS050
   CCSID UNICODE
   APPEND NO
   AUDIT NONE
   DATA CAPTURE NONE
   NOT VOLATILE
;

CREATE UNIQUE INDEX AUX0501
    ON LDGR_HDR
   (
	LDGR_ID     ASC
   )
     NOT CLUSTER
---- NOT PARTITIONED
     DEFINE YES
     NOT PADDED
     COMPRESS NO
     BUFFERPOOL BP16K2
     USING STOGROUP AUGS01
         PRIQTY 72000
         SECQTY -1
         ERASE NO
     PCTFREE  10
     FREEPAGE 8
     CLOSE YES
     COPY NO
     DEFER NO
     GBPCACHE CHANGED
     PIECESIZE 64G
;

CREATE INDEX AUX0502
    ON LDGR_HDR
   (
	MBR_ID      ASC
   )
     CLUSTER
---- NOT PARTITIONED
     DEFINE YES
     NOT PADDED
     COMPRESS NO
     BUFFERPOOL BP16K2
     USING STOGROUP AUGS01
         PRIQTY 72000
         SECQTY -1
         ERASE NO
     PCTFREE  10
     FREEPAGE 8
     CLOSE YES
     COPY NO
     DEFER NO
     GBPCACHE CHANGED
     PIECESIZE 64G
;



CREATE DATABASE AUDS6051
	BUFFERPOOL BP16K4
	INDEXBP BP16K2
	STOGROUP AUGS01
	CCSID UNICODE;

CREATE  TABLESPACE AUS051
        IN AUDS6051
        USING STOGROUP AUGS01
           PRIQTY 180000
           SECQTY -1
           ERASE NO
        BUFFERPOOL BP16K4
        FREEPAGE 8
        PCTFREE  10
              FOR UPDATE -1
        MAXPARTITIONS 100
        SEGSIZE 64
        DSSIZE 64G
----    NO MEMBER CLUSTER
        GBPCACHE CHANGED
        LOCKSIZE ROW
        LOCKMAX SYSTEM
        MAXROWS 255
        TRACKMOD NO
        CLOSE YES
        COMPRESS YES
        DEFINE YES
        LOGGED
        CCSID UNICODE
    ;

CREATE TABLE LDGR_SUM
(
	LDGR_SUM_ID           BIGINT NOT NULL,
	ACCUM_TYP_NM          VARCHAR(25),
	MBR_ID                VARCHAR(16),
	NTWK_CD               CHAR(3),
	NTWK_TIER_NM          VARCHAR(10),
	END_DT                DATE,
	EFF_DT                DATE,
	PLN_ID                INTEGER,
	SUB_ID                VARCHAR(16),
	AMT                   DECIMAL(10,2),
	MAX_AMT               DECIMAL(10,2),
	MAX_VST_CNT           INTEGER,
	UOM_NM                VARCHAR(10),
	PRIMARY KEY(LDGR_SUM_ID)
   )
   IN AUDS6051.AUS051
   CCSID UNICODE
   APPEND NO
   AUDIT NONE
   DATA CAPTURE NONE
   NOT VOLATILE
;

CREATE UNIQUE INDEX AUX0511
    ON LDGR_SUM 
   (
    LDGR_SUM_ID    ASC
   )
     NOT CLUSTER
---- NOT PARTITIONED
     DEFINE YES
     NOT PADDED
     COMPRESS NO
     BUFFERPOOL BP16K2
     USING STOGROUP AUGS01
         PRIQTY 72000
         SECQTY -1
         ERASE NO
     PCTFREE  10
     FREEPAGE 8
     CLOSE YES
     COPY NO
     DEFER NO
     GBPCACHE CHANGED
     PIECESIZE 64G
;

CREATE UNIQUE INDEX AUX0512
    ON LDGR_SUM
   (
     ACCUM_TYP_NM    ASC
   , MBR_ID          ASC
   , NTWK_CD         ASC
   , NTWK_TIER_NM    ASC
   , END_DT          ASC
   )
     NOT CLUSTER
---- NOT PARTITIONED
     DEFINE YES
     NOT PADDED
     COMPRESS NO
     BUFFERPOOL BP16K2
     USING STOGROUP AUGS01
         PRIQTY 72000
         SECQTY -1
         ERASE NO
     PCTFREE  10
     FREEPAGE 8
     CLOSE YES
     COPY NO
     DEFER NO
     GBPCACHE CHANGED
     PIECESIZE 64G
;

CREATE INDEX AUX0513
    ON LDGR_SUM
   (
    MBR_ID        ASC
   )
     CLUSTER
---- NOT PARTITIONED
     DEFINE YES
     NOT PADDED
     COMPRESS NO
     BUFFERPOOL BP16K2
     USING STOGROUP AUGS01
         PRIQTY 72000
         SECQTY -1
         ERASE NO
     PCTFREE  10
     FREEPAGE 8
     CLOSE YES
     COPY NO
     DEFER NO
     GBPCACHE CHANGED
     PIECESIZE 64G
;



CREATE DATABASE AUDS6052
	BUFFERPOOL BP16K4
	INDEXBP BP16K2
	STOGROUP AUGS01
	CCSID UNICODE;

CREATE  TABLESPACE AUS052
        IN AUDS6052
        USING STOGROUP AUGS01
           PRIQTY 180000
           SECQTY -1
           ERASE NO
        BUFFERPOOL BP16K4
        FREEPAGE 8
        PCTFREE  10
              FOR UPDATE -1
        MAXPARTITIONS 100
        SEGSIZE 64
        DSSIZE 64G
----    NO MEMBER CLUSTER
        GBPCACHE CHANGED
        LOCKSIZE ROW
        LOCKMAX SYSTEM
        MAXROWS 255
        TRACKMOD NO
        CLOSE YES
        COMPRESS YES
        DEFINE YES
        LOGGED
        CCSID UNICODE
    ;

CREATE TABLE LDGR_ENTRY
(
	LDGR_ENTRY_ID         BIGINT NOT NULL
	, PRIMY_LDGR_ENTRY_ID   BIGINT,
	LDGR_ID               BIGINT NOT NULL,
	ACCUM_TYP_NM          VARCHAR(25),
	ROLE_NM               VARCHAR(10),
	CST_SHR_TIER_NM       VARCHAR(10),
	AMT                   DECIMAL(10,2),
	NTWK_CD               CHAR(3),
	SNPSHT_SUM_AMT        DECIMAL(10,2),
	UOM_NM                VARCHAR(10),
	SVC_DT                DATE,
	PRIMARY KEY (LDGR_ENTRY_ID)
   )
   IN AUDS6052.AUS052
   CCSID UNICODE
   APPEND NO
   AUDIT NONE
   DATA CAPTURE NONE
   NOT VOLATILE
;

CREATE UNIQUE INDEX AUX0521
    ON LDGR_ENTRY
   (
     LDGR_ENTRY_ID        ASC
   )
     NOT CLUSTER
---- NOT PARTITIONED
     DEFINE YES
     NOT PADDED
     COMPRESS NO
     BUFFERPOOL BP16K2
     USING STOGROUP AUGS01
         PRIQTY 72000
         SECQTY -1
         ERASE NO
     PCTFREE  10
     FREEPAGE 8
     CLOSE YES
     COPY NO
     DEFER NO
     GBPCACHE CHANGED
     PIECESIZE 64G
;

CREATE INDEX AUX0522
    ON LDGR_ENTRY
   (
     LDGR_ID          ASC
   )
     NOT CLUSTER
---- NOT PARTITIONED
     DEFINE YES
     NOT PADDED
     COMPRESS NO
     BUFFERPOOL BP16K2
     USING STOGROUP AUGS01
         PRIQTY 72000
         SECQTY -1
         ERASE NO
     PCTFREE  10
     FREEPAGE 8
     CLOSE YES
     COPY NO
     DEFER NO
     GBPCACHE CHANGED
     PIECESIZE 64G
;

CREATE INDEX AUX0523
    ON LDGR_ENTRY
   (
     PRIMY_LDGR_ENTRY_ID  ASC
   )
     NOT CLUSTER
---- NOT PARTITIONED
     DEFINE YES
     NOT PADDED
     COMPRESS NO
     BUFFERPOOL BP16K2
     USING STOGROUP AUGS01
         PRIQTY 72000
         SECQTY -1
         ERASE NO
     PCTFREE  10
     FREEPAGE 8
     CLOSE YES
     COPY NO
     DEFER NO
     GBPCACHE CHANGED
     PIECESIZE 64G
;
